server:
  port: 8081
  servlet:
    context-path: /admin
  compression:
    enabled: true
    mime-types: text/html,text/css,application/javascript,application/json

  session:
    store-type: REDIS
    redis:
      namespace: spring:session # Namespace for keys used to store session.
      flush-mode: on_save # Session flush mode.
  redis:
    host: "localhost"
    port: 6379
    database: 0
  application:
    name: システム管理者向けアプリケーション # アプリケーション名
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss.SSS
    time-zone: Asia/Tokyo
    visibility:
      field: any
      getter: none
      setter: none
  profiles:
    active: develop
  devtools:
    restart:
      # 再起動のトリガーから除外するファイルを指定する
      exclude: static/**, public/**
      # 再起動のトリガーから除外するファイルを追加で指定する
      additional-exclude: java/**, test/**
  security:
    user:
      name: user
      password: user

logging:
  file:
    name: ./build/logs/application.log

management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false