spring:
  devtools:
    add-properties: true
  # THYMELEAF (ThymeleafAutoConfiguration)
  thymeleaf:
    cache: false
    mode: HTML
  # INTERNATIONALIZATION (MessageSourceAutoConfiguration)
  messages:
    basename: messages
    encoding: UTF-8
    cache-duration: -1
  r2dbc:
    #     url: jdbc:postgresql://localhost:5432/sample
    #    username: user
    #    password: password
    #    initialization-mode: always
    url: r2dbc:h2:file:///./build/db/testDb
    name: sa
    password:
    # url: r2dbc:postgresql://localhost:5432/sample
    # username: user
    # password: password
  flyway:
    # url: jdbc:postgresql://localhost:5432/sample
    url: jdbc:h2:file:./build/db/testDb
    # migrationファイルの配置ディレクトリー
    locations: classpath:db/migration
  h2:
    console:
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
  data:
    redis:
      host: "localhost"
      port: 6379
      database: 0
  boot:
    admin:
      client:
        url: http://localhost:8090/admin
        instance:
          service-host-type: ip

management:
  endpoint:
    health:
      show-details: ALWAYS
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false
  auditevents:
    enabled: true
  httpexchanges:
    recording:
      enabled: true
      include: RESPONSE_HEADERS