spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8888"
  boot:
    admin:
      client:
        url: http://localhost:8090/admin
        instance:
          service-host-type: ip

management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"


