server:
  port: 8082
  compression:
    enabled: true
    mime-types: text/html,text/css,application/javascript,application/json
  servlet:
    register-default-servlet: true
spring:
  profiles.default: unit
  mvc.favicon.enabled: false
  resources:
    cache:
      period: 86400
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  main:
    lazy-initialization: true
    allow-bean-definition-overriding: true
  redis:
    host: "localhost"
    port: 6379
    database: 0
  application:
    name: front # アプリケーション名
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss.SSS
    time-zone: Asia/Tokyo
    visibility:
      field: any
      getter: none
      setter: none
  devtools:
    restart:
      # 再起動のトリガーから除外するファイルを指定する
      exclude: static/**, public/**
      # 再起動のトリガーから除外するファイルを追加で指定する
      additional-exclude: java/**, test/**

logging:
  file:
    name: ./build/logs/WebFrontApplication.log

