server:
  port: 8090
  servlet:
    context-path: /admin

spring:
  application:
    name: admin # アプリケーション名
  boot:
    admin:
      client:
        url: http://localhost:8090/admin
        instance:
          service-host-type: ip
  thymeleaf:
    check-template-location: false

logging:
  file:
    name: ./build/logs/AdministratorApplication.log

management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false